FROM 351563604431.dkr.ecr.us-west-2.amazonaws.com/oryd/kratos


COPY admin.schema.json /etc/config/kratos/admin.schema.json
COPY person.schema.json /etc/config/kratos/person.schema.json
COPY oidc.google.jsonnet /etc/config/kratos/oidc.google.jsonnet
COPY prod/kratos.yml /etc/config/kratos/kratos.yml
COPY templates /templates