// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.3
// source: private/internal_dynamic_settings.proto

package private

import (
	dynamic_setting "github.com/featureguards/featureguards-go/v2/proto/dynamic_setting"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentDynamicSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartingVersion int64                             `protobuf:"varint,2,opt,name=starting_version,json=startingVersion,proto3" json:"starting_version,omitempty"`
	EndingVersion   int64                             `protobuf:"varint,3,opt,name=ending_version,json=endingVersion,proto3" json:"ending_version,omitempty"`
	DynamicSettings []*dynamic_setting.DynamicSetting `protobuf:"bytes,4,rep,name=dynamic_settings,json=dynamicSettings,proto3" json:"dynamic_settings,omitempty"`
}

func (x *EnvironmentDynamicSettings) Reset() {
	*x = EnvironmentDynamicSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_internal_dynamic_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvironmentDynamicSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentDynamicSettings) ProtoMessage() {}

func (x *EnvironmentDynamicSettings) ProtoReflect() protoreflect.Message {
	mi := &file_private_internal_dynamic_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentDynamicSettings.ProtoReflect.Descriptor instead.
func (*EnvironmentDynamicSettings) Descriptor() ([]byte, []int) {
	return file_private_internal_dynamic_settings_proto_rawDescGZIP(), []int{0}
}

func (x *EnvironmentDynamicSettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvironmentDynamicSettings) GetStartingVersion() int64 {
	if x != nil {
		return x.StartingVersion
	}
	return 0
}

func (x *EnvironmentDynamicSettings) GetEndingVersion() int64 {
	if x != nil {
		return x.EndingVersion
	}
	return 0
}

func (x *EnvironmentDynamicSettings) GetDynamicSettings() []*dynamic_setting.DynamicSetting {
	if x != nil {
		return x.DynamicSettings
	}
	return nil
}

var File_private_internal_dynamic_settings_proto protoreflect.FileDescriptor

var file_private_internal_dynamic_settings_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x1a, 0x1c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xca, 0x01, 0x0a, 0x1a, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x29, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x4a, 0x0a, 0x10, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x1b, 0x5a,
	0x19, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_private_internal_dynamic_settings_proto_rawDescOnce sync.Once
	file_private_internal_dynamic_settings_proto_rawDescData = file_private_internal_dynamic_settings_proto_rawDesc
)

func file_private_internal_dynamic_settings_proto_rawDescGZIP() []byte {
	file_private_internal_dynamic_settings_proto_rawDescOnce.Do(func() {
		file_private_internal_dynamic_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_private_internal_dynamic_settings_proto_rawDescData)
	})
	return file_private_internal_dynamic_settings_proto_rawDescData
}

var file_private_internal_dynamic_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_private_internal_dynamic_settings_proto_goTypes = []interface{}{
	(*EnvironmentDynamicSettings)(nil),     // 0: private.EnvironmentDynamicSettings
	(*dynamic_setting.DynamicSetting)(nil), // 1: dynamic_setting.DynamicSetting
}
var file_private_internal_dynamic_settings_proto_depIdxs = []int32{
	1, // 0: private.EnvironmentDynamicSettings.dynamic_settings:type_name -> dynamic_setting.DynamicSetting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_private_internal_dynamic_settings_proto_init() }
func file_private_internal_dynamic_settings_proto_init() {
	if File_private_internal_dynamic_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_private_internal_dynamic_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvironmentDynamicSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_private_internal_dynamic_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_internal_dynamic_settings_proto_goTypes,
		DependencyIndexes: file_private_internal_dynamic_settings_proto_depIdxs,
		MessageInfos:      file_private_internal_dynamic_settings_proto_msgTypes,
	}.Build()
	File_private_internal_dynamic_settings_proto = out.File
	file_private_internal_dynamic_settings_proto_rawDesc = nil
	file_private_internal_dynamic_settings_proto_goTypes = nil
	file_private_internal_dynamic_settings_proto_depIdxs = nil
}
